INSERT INTO test.part (id, amount, name, necessary) VALUES (1, 3, 'Motherboard INTEL B150 1', true);
INSERT INTO test.part (id, amount, name, necessary) VALUES (2, 4, 'Motherboard INTEL B250 2', false);
INSERT INTO test.part (id, amount, name, necessary) VALUES (3, 5, 'Motherboard INTEL B250 3', true);
INSERT INTO test.part (id, amount, name, necessary) VALUES (4, 6, 'Motherboard INTEL B250 4', false);
INSERT INTO test.part (id, amount, name, necessary) VALUES (5, 7, 'Motherboard INTEL B250 5', true);
INSERT INTO test.part (id, amount, name, necessary) VALUES (6, 8, 'Motherboard INTEL B250 6', false);
INSERT INTO test.part (id, amount, name, necessary) VALUES (7, 9, 'Motherboard INTEL B250 7', true);
INSERT INTO test.part (id, amount, name, necessary) VALUES (8, 33, 'Motherboard INTEL B250 8', false);
INSERT INTO test.part (id, amount, name, necessary) VALUES (9, 31, 'Motherboard INTEL B250 9', true);
INSERT INTO test.part (id, amount, name, necessary) VALUES (10, 32, 'Motherboard INTEL B250 10', true);
INSERT INTO test.part (id, amount, name, necessary) VALUES (11, 2, 'ПРОЦЕССОР , 2 CORE, 3200MHZ, LGA1151, L3 2MB, INTEL GRAPHICS HD 610', true);
INSERT INTO test.part (id, amount, name, necessary) VALUES (12, 5, 'ВИДЕОКАРТА SVGA PCI EXPRESS, 2GB GDDR3, 64BIT, 800/5010MHZ, LP,VGA/DVI/HDMI', true);
INSERT INTO test.part (id, amount, name, necessary) VALUES (13, 4, 'ПРИВОД ВНЕШНИЙ DVD-RW , USB 2.0, BLACK, SLIM, RETAIL', false);
INSERT INTO test.part (id, amount, name, necessary) VALUES (14, 12, 'Карта звуковая PCI - 4CH (c-media 8738) Box (10715)', false);
INSERT INTO test.part (id, amount, name, necessary) VALUES (15, 33, 'Барбарбия кергуду', true);